modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="trials"
version="1.0.0"
displayName="Trials Towers"
displayURL="https://discord.gg/qGTuwEMgpT"
credits="Mojang"
authors="Jusey1"

[[dependencies.trials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




