modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="trials_towers"
version="1.0.0"
displayName="Trials Towers"
displayURL="https://discord.gg/qGTuwEMgpT"
credits="Mojang"
authors="Jusey1"

[[dependencies.trials_towers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.trials_towers]]
    modId="mace_port"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


